id = 0
type = 'finger'
code = '2-11-11'
fingertip_scale_factor = (1.0, 1.0, 1.0)
link_added_length_mm_list = [10.0, 10.0, 10.0, 10.0, 10.0]
pad_resolution_level = 2
pad_thickness_mm = 1.0
bump_edge_zeroing_spread = 0.3
bump_type_list = ['gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian']
bump_number_list = [0, 0, 0, 0, 0]
bump_max_height_intensity_mm_list = [0.0, 0.0, 0.0, 0.0, 0.0]
bump_height_intensity_list = [[], [], [], [], []]
bumps_spread_list = [[], [], [], [], []]
bumps_aspect_ratio_list = [[], [], [], [], []]
bump_rotation_deg_list = [[], [], [], [], []]
bump_center_angle_deg_list = [[], [], [], [], []]
bump_center_offset_list = [[], [], [], [], []]
motor_small_surface_dim_mm = (18, 18)
motor_large_surface_dim_mm = (18, 28)
max_add_joint_slots = 5
rotation_mode = '2'
mode = 'fixed'
