id = 2
type = 'finger'
code = '110-11-0101010101'
fix = True
fingertip_scale_factor = (1.0, 1.0, 1.0)
initial_link_added_length_mm = 0.0
link_added_length_mm_list = []
pad_resolution_level = 2
pad_thickness_mm = 1.0
bump_edge_zeroing_spread = 0.3
initial_bump_type = 'gaussian'
initial_bump_number = 0
initial_bump_max_height_intensity_mm = 0.0
initial_bump_height_intensity = 1
initial_bumps_spread = 0.25
initial_bumps_aspect_ratio = 1.0
initial_bump_rotation_deg = 0
initial_bump_center_angle_deg = 0.0
initial_bump_center_offset = 0.0
bump_type_list = ['gaussian', 'gaussian', 'gaussian', 'gaussian', 'gaussian']
bump_number_list = [0, 0, 0, 0, 0]
bump_max_height_intensity_mm_list = [0.0, 0.0, 0.0, 0.0, 0.0]
bump_height_intensity_list = [[], [], [], [], []]
bumps_spread_list = [[], [], [], [], []]
bumps_aspect_ratio_list = [[], [], [], [], []]
bump_rotation_deg_list = [[], [], [], [], []]
bump_center_angle_deg_list = [[], [], [], [], []]
bump_center_offset_list = [[], [], [], [], []]
motor_small_surface_dim_mm = (18, 18)
motor_large_surface_dim_mm = (18, 28)
initial_min_add_joint = 2
initial_max_add_joint = 5
initial_rotation_mode = ('000', '100', '101', '110', '111')
initial_add_joint_type = ('01', '10')
add_joint_type = '01'
rotation_mode = '110'
min_add_joint = 1
max_add_joint = 3
add_joint = 2
before_joints = 1
after_joints = 1
add_joint_type_str = '0101010101'
mode = 'fixed'
