id = 0
type = 'thumb_right'
code = '1-2-10101010'
fix = True
fingertip_scale_factor = (1.0, 1.0, 1.0)
initial_link_added_length_mm = 0.0
link_added_length_mm_list = []
pad_resolution_level = 2
pad_thickness_mm = 1.0
bump_edge_zeroing_spread = 0.3
initial_bump_type = 'gaussian'
initial_bump_number = 0
initial_bump_max_height_intensity_mm = 0.0
initial_bump_height_intensity = 1
initial_bumps_spread = 0.25
initial_bumps_aspect_ratio = 1.0
initial_bump_rotation_deg = 0
initial_bump_center_angle_deg = 0.0
initial_bump_center_offset = 0.0
bump_type_list = ['gaussian', 'gaussian', 'gaussian', 'gaussian']
bump_number_list = [0, 0, 0, 0]
bump_max_height_intensity_mm_list = [0.0, 0.0, 0.0, 0.0]
bump_height_intensity_list = [[], [], [], []]
bumps_spread_list = [[], [], [], []]
bumps_aspect_ratio_list = [[], [], [], []]
bump_rotation_deg_list = [[], [], [], []]
bump_center_angle_deg_list = [[], [], [], []]
bump_center_offset_list = [[], [], [], []]
motor_small_surface_dim_mm = (18, 18)
motor_large_surface_dim_mm = (18, 28)
initial_min_add_joint = 2
initial_max_add_joint = 4
initial_rotation_mode = ('0', '1')
initial_add_joint_type = ('01', '10')
add_joint_type = '01'
rotation_mode = '1'
min_add_joint = 2
max_add_joint = 2
add_joint = 2
before_joints = 0
after_joints = 2
add_joint_type_str = '10101010'
mode = 'fixed'
