"""Render one short clip per parameter in the paper's SHAP plot, over the optimizer's own search ranges.

Ranges come from iros_paper_codebase/optimization/nested_optimizer_v2.py (NestedOptimizationConfig).
Geometry is generated by generation_v2 (as for every other website animation); paper digit indices map to
the approved hand as F0 = right finger (green, beside the thumb), F1 = middle (yellow), F2 = left (blue).

  python -B website_assets/scripts/build_shap_parameters.py --preview   # min / mid / max keyframes only
  python -B website_assets/scripts/build_shap_parameters.py             # all frames, then encode
"""
import sys
sys.dont_write_bytecode=True
from pathlib import Path
import argparse,copy,hashlib,json,math,os,subprocess
from concurrent.futures import ThreadPoolExecutor,as_completed
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
GEN=ROOT.parent/'generation_v2'
OUT=ROOT/'preview/shap-parameters'
WEB=ROOT/'v2/media/params'
BLENDER='C:/Program Files/Blender Foundation/Blender 5.2/blender.exe'
SAMPLES=25          # unique native renders per continuous clip
FPS,LOOP=30,96      # 3.2 s loops

BASE=dict(thumb_location=0.960893225208987,locations=[0.14669345741136156,0.25369307040740413,0.36069268340344673],
          identities=[3,2,1],angles_deg=[0.,0.,0.],normal_offsets_mm=[0.,0.,0.],side_offsets_mm=[0.,0.,0.],
          thumb_angle_deg=0.,thumb_normal_offset_mm=0.,thumb_side_offset_mm=0.,
          finger_codes=['2-1-1']*3,thumb_code='1--22',finger_tip_scales=[[1.,1.,1.]]*3,thumb_tip_scale=[1.,1.,1.],
          finger_link_mm=[0,0,0],thumb_link_mm=0,palm_surface=None)
# Two palm kernels (K0, K1) at mid-range values, used as the fixed context for the kernel clips.
KERNELS=dict(height_mm=12.,height_intensity=[1.,.8],spread=[.18,.14],aspect_ratio=[1.,1.],rotation_deg=[0.,0.],
             center_angle_deg=[40.,215.],center_offset=[.55,.5])
NO_PADS=[[] for _ in range(3)]

def digit(field,i):
    def set_(f,v):f[field][i]=v
    return set_
def thumb(field):
    def set_(f,v):f[field]=v
    return set_
def tips(axis):
    def set_(f,v):
        f['finger_tip_scales']=[[v if a==axis else 1. for a in range(3)] for _ in range(3)]
        f['thumb_tip_scale']=[v if a==axis else 1. for a in range(3)]
    return set_
def kernel(key,k):
    def set_(f,v):f['palm_surface'][key][k]=v
    return set_
def deform(f,v):f['palm_surface']['height_mm']=v

# id, SHAP label, setter, range (paper), kernel context, integer, cyclic
CONTINUOUS=[
    ('normal-offset-t','Normal Offset [T]',thumb('thumb_normal_offset_mm'),(-30,30)),
    ('normal-offset-f0','Normal Offset [F0]',digit('normal_offsets_mm',0),(0,5)),
    ('normal-offset-f1','Normal Offset [F1]',digit('normal_offsets_mm',1),(0,10)),
    ('normal-offset-f2','Normal Offset [F2]',digit('normal_offsets_mm',2),(0,5)),
    ('side-offset-f0','Side Offset [F0]',digit('side_offsets_mm',0),(0,30)),
    ('side-offset-f2','Side Offset [F2]',digit('side_offsets_mm',2),(-30,0)),
    ('side-offset-t','Side Offset [T]',thumb('thumb_side_offset_mm'),(-40,10)),
    ('angle-f0','Angle [F0]',digit('angles_deg',0),(0,30)),
    ('angle-f2','Angle [F2]',digit('angles_deg',2),(-30,0)),
    ('angle-t','Angle [T]',thumb('thumb_angle_deg'),(-30,30)),
    ('link-length-f0','Added Link Length [F0]',digit('finger_link_mm',0),(0,10),'int'),
    ('link-length-f1','Added Link Length [F1]',digit('finger_link_mm',1),(0,10),'int'),
    ('link-length-f2','Added Link Length [F2]',digit('finger_link_mm',2),(0,10),'int'),
    ('link-length-t','Added Link Length [T]',thumb('thumb_link_mm'),(0,10),'int'),
    ('fingertip-scale-y','Fingertip Scale Y',tips(1),(1,1.5)),
    ('fingertip-scale-z','Fingertip Scale Z',tips(2),(.5,1.5)),
    ('max-surface-deform','Max Surface Deform',deform,(0,20),'kernels'),
]
for k in (0,1):
    CONTINUOUS+=[
        (f'center-offset-k{k}',f'Center Offset [K{k}]',kernel('center_offset',k),(0,1),'kernels'),
        (f'center-angle-k{k}',f'Center Angle [K{k}]',kernel('center_angle_deg',k),(0,360),'kernels','cyclic'),
        (f'spread-k{k}',f'Spread [K{k}]',kernel('spread',k),(.05,.3),'kernels'),
        (f'intensity-ratio-k{k}',f'Intensity Ratio [K{k}]',kernel('height_intensity',k),(0,1),'kernels'),
    ]

def drop_f2(f):
    for key in ('locations','identities','angles_deg','normal_offsets_mm','side_offsets_mm','finger_codes','finger_tip_scales','finger_link_mm'):
        f[key]=f[key][:2]
def codes_a(f):f['finger_codes']=['1-1-1']*len(f['locations'])
def codes_b(f):f['finger_codes']=['0--111']*len(f['locations'])
def thumb_a(f):f['thumb_code']='1--11'
def thumb_b(f):f['thumb_code']='0--11'
DISCRETE=[
    ('finger-number','Finger Number',[('3 fingers',lambda f:None),('2 fingers',drop_f2)]),
    ('finger-code','Finger Code',[('code A',codes_a),('code B',codes_b)]),
    ('thumb-code','Thumb Code',[('code A',thumb_a),('code B',thumb_b)]),
]

def plan():
    frames,clips=[],[]
    def add(f):f['index']=len(frames);frames.append(f);return f['index']
    for spec in CONTINUOUS:
        cid,label,setter,(lo,hi)=spec[:4];flags=spec[4:]
        cyclic='cyclic' in flags;n=SAMPLES-1 if cyclic else SAMPLES
        idx,values=[],[]
        for s in range(n):
            v=lo+(hi-lo)*s/(SAMPLES-1)
            if 'int' in flags:v=round(v)
            f=copy.deepcopy(BASE);f['clip']=cid;f['name']=f'{cid}-{s:02d}';f['value']=v
            if 'kernels' in flags:f['palm_surface']=copy.deepcopy(KERNELS);f['finger_surfaces']=NO_PADS;f['thumb_surfaces']=[]
            setter(f,v);idx.append(add(f));values.append(v)
        if cyclic:order=[idx[(k*n)//LOOP] for k in range(LOOP)]
        else:order=[idx[round((n-1)*(1-math.cos(2*math.pi*k/LOOP))/2)] for k in range(LOOP)]
        clips.append(dict(id=cid,label=label,range=[lo,hi],values=values,frames=idx,order=order,
                          keyframes=[idx[0],idx[len(idx)//2],idx[-1]],poster=idx[-1] if not cyclic else idx[len(idx)//3]))
    for cid,label,states in DISCRETE:
        idx=[]
        for s,(name,mutate) in enumerate(states):
            f=copy.deepcopy(BASE);f['clip']=cid;f['name']=f'{cid}-{s:02d}';f['value']=name;mutate(f);idx.append(add(f))
        order=[idx[0]]*(LOOP//2)+[idx[1]]*(LOOP//2)
        clips.append(dict(id=cid,label=label,range=[s[0] for s in states],values=[s[0] for s in states],frames=idx,order=order,keyframes=idx,poster=idx[1]))
    schedule=dict(frames=frames,clips=clips,fps=FPS,loop_frames=LOOP,camera_scale=.54,
                  source_hashes={str(p.relative_to(GEN)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(GEN.rglob('*')) if p.suffix in ('.py','.blend')},
                  ranges_source='iros_paper_codebase/optimization/nested_optimizer_v2.py',
                  digit_map={'F0':'right finger (green), beside the thumb','F1':'middle finger (yellow)','F2':'left finger (blue)','T':'thumb (red)'})
    OUT.mkdir(parents=True,exist_ok=True);(OUT/'plan.json').write_text(json.dumps(schedule,indent=2))
    return schedule

def render(indices):
    temp=OUT/'tmp'/f'process-{indices[0]}';temp.mkdir(parents=True,exist_ok=True)
    logs=OUT/'logs';logs.mkdir(exist_ok=True);path=logs/f'batch-{indices[0]:04d}.log'
    with path.open('w',encoding='utf-8') as log:
        result=subprocess.run([BLENDER,'-b','--factory-startup','-t','4','--python-exit-code','1','--python',
            str(ROOT/'scripts/render_shap_parameters.py'),'--','--indices',*map(str,indices)],
            env=dict(os.environ,PYTHONDONTWRITEBYTECODE='1',TEMP=str(temp),TMP=str(temp)),
            stdout=log,stderr=subprocess.STDOUT,creationflags=subprocess.CREATE_NO_WINDOW)
    if result.returncode:raise RuntimeError(path.read_text(encoding='utf-8',errors='replace')[-4000:])
    print(f'BATCH_COMPLETE {indices[0]}-{indices[-1]}',flush=True)

def run_all(indices,workers):
    names={f['index']:f['name'] for f in json.loads((OUT/'plan.json').read_text())['frames']}
    missing=[i for i in indices if not (OUT/'frames'/f'{names[i]}.json').exists()]
    batches=[missing[i:i+12] for i in range(0,len(missing),12)]
    with ThreadPoolExecutor(max_workers=workers) as pool:
        for r in as_completed([pool.submit(render,b) for b in batches]):r.result()

def crop_box(frames):
    # union of projected bounds over every frame, in the 1200 x 1000 raw render, padded and widened to 4:3
    meta=[json.loads((OUT/'frames'/f"{f['name']}.json").read_text())['bounds'] for f in frames]
    l=min(b[0] for b in meta)*1200-40;r=max(b[2] for b in meta)*1200+40
    t=(1-max(b[3] for b in meta))*1000-40;b_=(1-min(b[1] for b in meta))*1000+40
    w,h=r-l,b_-t
    if w/h<4/3:l-=(h*4/3-w)/2;w=h*4/3
    else:t-=(w*3/4-h)/2;h=w*3/4
    l,t=max(0,l),max(0,t);w,h=min(w,1200-l),min(h,1000-t)
    return tuple(int(round(v)) for v in (l,t,l+w,t+h))

def sheet(schedule,keys,path):
    clips=schedule['clips'];W=300;H=250
    img=Image.new('RGB',(W*3,H*len(clips)),'white')
    for r,c in enumerate(clips):
        for k,i in enumerate(c[keys][:3]):
            p=OUT/'frames'/f"{schedule['frames'][i]['name']}.png"
            if p.exists():img.paste(Image.open(p).convert('RGB').resize((W,H)),(k*W,r*H))
    img.save(path)

def encode(schedule):
    WEB.mkdir(parents=True,exist_ok=True)
    catalog=[]
    for c in schedule['clips']:
        cache={};box=crop_box([schedule['frames'][i] for i in c['frames']])   # per clip, like the approved media
        def frame(i):
            if i not in cache:
                im=Image.open(OUT/'frames'/f"{schedule['frames'][i]['name']}.png").convert('RGB')
                assert im.size==(1200,1000)
                im=im.crop(box);w,h=im.size
                # the clamped crop may not be 4:3; pad with white rather than stretch
                W,H=max(w,round(h*4/3)),max(h,round(w*3/4));canvas=Image.new('RGB',(W,H),'white')
                canvas.paste(im,((W-w)//2,(H-h)//2));cache[i]=canvas.resize((640,480),Image.Resampling.LANCZOS)
            return cache[i]
        video=WEB/f"{c['id']}.mp4"
        proc=subprocess.Popen(['ffmpeg','-y','-loglevel','error','-f','rawvideo','-pix_fmt','rgb24','-s','640x480','-r',str(FPS),'-i','-',
            '-an','-c:v','libx264','-preset','slow','-crf','23','-pix_fmt','yuv420p','-movflags','+faststart',str(video)],stdin=subprocess.PIPE)
        for i in c['order']:proc.stdin.write(frame(i).tobytes())
        proc.stdin.close();assert proc.wait()==0
        frame(c['poster']).save(WEB/f"{c['id']}.webp",quality=86)
        catalog.append(dict(id=c['id'],label=c['label'],range=c['range'],crop=box,video=f"media/params/{c['id']}.mp4",poster=f"media/params/{c['id']}.webp"))
    (WEB/'catalog.json').write_text(json.dumps(dict(clips=catalog),indent=2))
    print(f'ENCODED {len(catalog)} clips',flush=True)

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--preview',action='store_true');ap.add_argument('--workers',type=int,default=3)
    ap.add_argument('--encode-only',action='store_true');args=ap.parse_args()
    schedule=plan()
    if not args.encode_only:
        wanted=[i for c in schedule['clips'] for i in (c['keyframes'] if args.preview else c['frames'])]
        run_all(wanted,args.workers)
    if args.preview:sheet(schedule,'keyframes',OUT/'preview-sheet.png');print('PREVIEW',OUT/'preview-sheet.png');return
    encode(schedule)

if __name__=='__main__':main()
